name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Ensure package cache folder exists
        run: mkdir -p ~/.xmake/packages

      - name: Ensure build cache folder exists
        run: mkdir -p build/.xmake

      - name: Cache xmake packages
        uses: actions/cache@v3
        with:
          path: ~/.xmake/packages
          key: ${{ runner.os }}-xmake-packages-${{ hashFiles('xmake.lua') }}

      - name: Cache xmake build
        uses: actions/cache@v3
        with:
          path: build/.xmake
          key: ${{ runner.os }}-xmake-build-${{ hashFiles('xmake.lua') }}

      - name: Setup
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          package-cache-key: 'stfc-mod-ci-win'

      - name: Configure
        run: xmake f -m release -y

      - name: Build
        run: xmake -y

      - name: Package
        run: |
          mv build/windows/x64/release/stfc-community-patch.dll version.dll

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stfc-community-patch
          path: version.dll
